name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get Docker version
      run: echo "APP_VERSION=$(cat version.txt)" >> $GITHUB_ENV
    - name: Output Docker ver
      run: echo $APP_VERSION
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$APP_VERSION
